apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "example-angular-order.fullname" . }}
  labels:
  {{- include "example-angular-order.labels" . | nindent 4 }}
data:
  app.config.json: |-
    {{- if .Values.configMap.values }}
    {{- .Values.configMap.values | nindent 4 }}
  {{- end }}
